### ISSUE TITLE
Release in WN-LMF 1.1

### ISSUE THREAD

**Issue by goodmami** [bond-lab/omw-data#3]
When the WN-LMF 1.1 format is merged (see globalwordnet/schemas#38) we should release the OMW data in that format. The main thing is adding `<Requires id="pwn" version="3.0" />` elements on the "expand" wordnets. Also the `<SyntacticBehaviour>` elements in the PWN files can be relocated. Anything else? Are we replacing `<Sense>` ids with the value of their `dc:identifier` attribute?

**Comment by goodmami** [comment]
With synsets linked by ILIs instead of PWN synset IDs, we don't really need to depend on PWN 3.0. For the next release, should they depend on PWN 3.1, EWN 2020, or EWN 2021 (coming in April?) instead?

**Comment by goodmami** [comment]
Somewhat related to this: why don't we split the examples from the definitions in the PWN's WN-LMF files? Was there a reliable automatic method that the EWN used, or was manual effort required?

Related:
* https://github.com/nltk/nltk/issues/2527
* https://github.com/globalwordnet/english-wordnet/issues/143

Also here's the code used by [gwn-scala-api](https://github.com/jmccrae/gwn-scala-api/) for extracting examples from the WNDB gloss:

https://github.com/jmccrae/gwn-scala-api/blob/742cd7cddee021b27c0e5681a4ea20b92d887e4c/src/main/scala/org/globalwordnet/wnapi/wndb.scala#L208-L222

**Comment by goodmami** [comment]
Here is a checklist of things that we should do. @fcbond would you prefer that I create individual local issues for those that don't already have one?

* PWN 3.0 and 3.1
  - [ ] #5: drop "Princeton" from the name, update ID, version, label, email, url, license (?)
  - [ ] #5: document differences with the WNDB data
  - [ ] #8: strip adjposition from adjective lemmas
  - [ ] #9: correct part of speech `s` on Lemmas
  - [ ] #10
  - [ ] #11: include all exceptions as Forms
  - [ ] Add `members` attribute on `<Synset>` (c.f. globalwordnet/english-wordnet#660)
  - [ ] Use sense key (properly escaped) as `<Sense>` ID (c.f. globalwordnet/english-wordnet#662)
  - [ ] Move `<SyntacticBehaviour>` elements from lexical entries to the lexicon level (c.f. globalwordnet/english-wordnet#661)
  - [ ] Move lexfile from `dc:subject` to `lexfile` attribute
* OMW other wordnets
  - [ ] Add `<Requires>`
  - [ ] Validate form of IDs (conforming to xsd:id)
  - [ ] anything else?

**Comment by fcbond** [comment]
I think we have done all of these, although sense key is not used as the sense ID, but rather stored as `dc:identifier`
